# Generated by Django 3.1.2 on 2020-10-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramLanguages',
            new_name='ProgramLanguage',
        ),
    ]
