# Generated by Django 3.1.2 on 2020-10-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0002_auto_20201003_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlanguage',
            name='desc',
        ),
        migrations.AddField(
            model_name='programlanguage',
            name='lang_brief_desc',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='programlanguage',
            name='lang_category',
            field=models.CharField(default='Individual', max_length=100),
        ),
        migrations.AddField(
            model_name='programlanguage',
            name='lang_img',
            field=models.ImageField(default='Individual', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='programlanguage',
            name='lang_short_desc',
            field=models.CharField(default='', max_length=2500),
        ),
        migrations.AlterField(
            model_name='programlanguage',
            name='lang_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
