# Generated by Django 3.1.2 on 2020-10-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0003_auto_20201005_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlanguage',
            name='lang_saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programlanguage',
            name='lang_img',
            field=models.ImageField(default='Individual', upload_to='plm/images'),
        ),
    ]
