# Generated by Django 3.1.2 on 2020-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0004_auto_20201005_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlanguage',
            name='lang_brief_desc',
            field=models.TextField(),
        ),
    ]
