# Generated by Django 3.1.2 on 2020-10-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0005_auto_20201007_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programlanguage',
            name='lang_short_desc',
            field=models.TextField(),
        ),
    ]
