# Generated by Django 3.1.2 on 2020-10-23 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plm', '0006_auto_20201015_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlanguage',
            name='lang_saved',
        ),
    ]
